export const VIA_COMMAND = {
    GET_PROTOCOL_VERSION: 0x01,
    DYNAMIC_KEYMAP_GET_KEYCODE: 0x04,
    DYNAMIC_KEYMAP_SET_KEYCODE: 0x05,
    DYNAMIC_KEYMAP_MACRO_GET_COUNT: 0x0c,
    DYNAMIC_KEYMAP_MACRO_GET_BUFFER_SIZE: 0x0d,
    DYNAMIC_KEYMAP_MACRO_GET_BUFFER: 0x0e,
    DYNAMIC_KEYMAP_MACRO_SET_BUFFER: 0x0f,
    DYNAMIC_KEYMAP_MACRO_RESET: 0x10,
    DYNAMIC_KEYMAP_GET_LAYER_COUNT: 0x11,
    DYNAMIC_KEYMAP_GET_BUFFER: 0x12,
    DYNAMIC_KEYMAP_SET_BUFFER: 0x13,
    DYNAMIC_KEYMAP_GET_ENCODER: 0x14,
    DYNAMIC_KEYMAP_SET_ENCODER: 0x15,
} as const;

export const VIA_REPORT_LENGTH = 32;
export const VIA_CHUNK_SIZE = 28;
export const GMK67_V2 = { vendorId: 0x36b0, productId: 0x3068, rows: 6, cols: 16 } as const;
